package danmu.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tb_danmu".
 */
public class DanMu {

    private int danMuId;
    /** Not-null value. */
    private String danMuText;
    private int danMuTick;

    public DanMu() {
    }

    public DanMu(int danMuId, String danMuText, int danMuTick) {
        this.danMuId = danMuId;
        this.danMuText = danMuText;
        this.danMuTick = danMuTick;
    }

    public int getDanMuId() {
        return danMuId;
    }

    public void setDanMuId(int danMuId) {
        this.danMuId = danMuId;
    }

    /** Not-null value. */
    public String getDanMuText() {
        return danMuText;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDanMuText(String danMuText) {
        this.danMuText = danMuText;
    }

    public int getDanMuTick() {
        return danMuTick;
    }

    public void setDanMuTick(int danMuTick) {
        this.danMuTick = danMuTick;
    }

}
